# Generated by Django 4.1.6 on 2023-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='HomeCarusel name')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeCarusel image')),
                ('info1', models.CharField(max_length=15, verbose_name='HomeCarusel info_1')),
                ('info2', models.CharField(blank=True, max_length=15, verbose_name='HomeCarusel info_2')),
            ],
        ),
    ]
