# Generated by Django 4.1.6 on 2023-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_homecarusel_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20, verbose_name='HomeTopic topic')),
                ('img', models.ImageField(upload_to='media/topics', verbose_name='HomeTopic image')),
                ('i_count', models.CharField(max_length=25, verbose_name='HomeTopic i_count')),
            ],
        ),
        migrations.AlterField(
            model_name='homecarusel',
            name='verified',
            field=models.Field(blank=True, verbose_name='HomeCarusel verified image'),
        ),
    ]
