# Generated by Django 4.1.6 on 2023-02-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_homecarusel_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecarusel',
            name='verified',
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='img2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='HomeCarusel image'),
        ),
    ]
