# Generated by Django 4.1.6 on 2023-02-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_homecarusel_verified_homecarusel_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarusel',
            name='img2',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='HomeCarusel img2 image'),
        ),
    ]
