# Generated by Django 4.1.6 on 2023-02-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_homecarusel_img2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometopic',
            name='img',
            field=models.ImageField(upload_to='media', verbose_name='HomeTopic image'),
        ),
    ]
