# Generated by Django 4.1.6 on 2023-02-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='ContactUs full_name')),
                ('email', models.EmailField(max_length=254, verbose_name='ContactUs email')),
                ('company', models.CharField(max_length=70, verbose_name='ContactUs company')),
                ('text', models.TextField(verbose_name='ContactUs text')),
            ],
        ),
    ]
