# Generated by Django 4.1.6 on 2023-02-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCarusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='HomeCarusel name')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeCarusel image')),
                ('info1', models.CharField(max_length=15, verbose_name='HomeCarusel info_1')),
                ('info2', models.CharField(blank=True, max_length=15, verbose_name='HomeCarusel info_2')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20, verbose_name='HomeTopic topic')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeTopic image')),
                ('i_count', models.CharField(max_length=25, verbose_name='HomeTopic i_count')),
            ],
        ),
    ]
