# Generated by Django 4.1.6 on 2023-02-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarusel',
            name='verified',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='HomeCarusel verified image'),
        ),
    ]
