# Generated by Django 4.1.6 on 2023-02-13 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homecarusel_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecarusel',
            name='verified',
        ),
    ]
