# Generated by Django 4.1.6 on 2023-02-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_homecarusel_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLatestEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='HomeLatestEpisode name')),
                ('img', models.ImageField(upload_to='media/podcast_poster', verbose_name='HomeLatestEpisode image')),
                ('info', models.CharField(max_length=115, verbose_name='HomeLatestEpisode info')),
                ('duration', models.PositiveIntegerField(verbose_name='HomeLatestEpisode duration')),
                ('episode_count', models.PositiveIntegerField(verbose_name='HomeLatestEpisode episode_count')),
            ],
        ),
    ]
