# Generated by Django 4.1.6 on 2023-02-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homelatestepisode'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelatestepisode',
            name='author',
            field=models.CharField(default=1, max_length=40, verbose_name='HomeLatestEpisode author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homelatestepisode',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='HomeLatestEpisode duration (min)'),
        ),
    ]
