# Generated by Django 4.1.6 on 2023-02-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homelatestepisode_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLatestEpisodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='HomeLatestEpisode name')),
                ('img', models.ImageField(upload_to='media/podcast_poster', verbose_name='HomeLatestEpisode image')),
                ('info', models.CharField(max_length=115, verbose_name='HomeLatestEpisode info')),
                ('duration', models.PositiveIntegerField(verbose_name='HomeLatestEpisode duration (min)')),
                ('episode_count', models.PositiveIntegerField(verbose_name='HomeLatestEpisode episode_count')),
                ('author', models.CharField(max_length=40, verbose_name='HomeLatestEpisode author')),
                ('author_info', models.CharField(max_length=20, verbose_name='HomeLatestEpisode author_info')),
                ('author_img', models.ImageField(upload_to='media/home_latest_auther', verbose_name='HomeLatestEpisode author_img')),
            ],
        ),
        migrations.DeleteModel(
            name='HomeLatestEpisode',
        ),
    ]
