# Generated by Django 4.1.6 on 2023-02-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_homelatestepisodes_delete_homelatestepisode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeLatestEpisodes',
            new_name='HomeLatestEpisode',
        ),
    ]
