# Generated by Django 4.1.6 on 2023-02-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_homelatestepisodes_homelatestepisode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTrendingEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='HomeTrendingEpisode name')),
                ('img', models.ImageField(upload_to='media/podcast_poster', verbose_name='HomeTrendingEpisode image')),
                ('info', models.CharField(max_length=115, verbose_name='HomeTrendingEpisode info')),
                ('author', models.CharField(max_length=40, verbose_name='HomeTrendingEpisode author')),
                ('author_info', models.CharField(max_length=20, verbose_name='HomeLatestEpisode author_info')),
                ('author_img', models.ImageField(upload_to='media/home_latest_auther', verbose_name='HomeTrendingEpisode author_img')),
            ],
        ),
    ]
