# Generated by Django 4.1.6 on 2023-02-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_homecarusel_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='HomeEpisode name')),
                ('img', models.ImageField(upload_to='media/podcast_poster', verbose_name='HomeEpisode image')),
                ('info', models.CharField(max_length=115, verbose_name='HomeEpisode info')),
                ('duration', models.PositiveIntegerField(verbose_name='HomeEpisode duration (min)')),
                ('episode_count', models.PositiveIntegerField(verbose_name='HomeEpisode episode_count')),
                ('author', models.CharField(max_length=40, verbose_name='HomeEpisode author')),
                ('author_info', models.CharField(max_length=20, verbose_name='HomeEpisode author_info')),
                ('author_img', models.ImageField(upload_to='media/home__auther', verbose_name='HomeEpisode author_img')),
            ],
        ),
        migrations.CreateModel(
            name='HomeGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20, verbose_name='HomeGenre topic')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeGenre image')),
                ('i_count', models.CharField(max_length=25, verbose_name='HomeGenre i_count')),
                ('story', models.TextField(verbose_name='HomeGenre story')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutPodcaster',
        ),
        migrations.DeleteModel(
            name='HomeLatestEpisode',
        ),
        migrations.DeleteModel(
            name='HomeTopic',
        ),
        migrations.DeleteModel(
            name='HomeTrendingEpisode',
        ),
    ]
