# Generated by Django 4.1.6 on 2023-02-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_homeepisode_homegenre_delete_aboutpodcaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecarusel',
            name='verified',
        ),
    ]
