# Generated by Django 4.1.6 on 2023-02-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_homeepisode_slug_homegenre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homegenre',
            name='slug',
        ),
    ]
