# Generated by Django 4.1.6 on 2023-02-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_homegenre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='homegenre',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='HomeGenre link'),
        ),
    ]
