# Generated by Django 4.1.6 on 2023-02-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_homegenre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarusel',
            name='boolean',
            field=models.BooleanField(default=1, verbose_name='Nout bool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homecarusel',
            name='verified',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='HomeCarusel verified image'),
        ),
    ]
