# Generated by Django 4.1.6 on 2023-02-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_homecarusel_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeepisode',
            name='slug',
        ),
    ]
