# Generated by Django 4.1.6 on 2023-02-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_remove_homeepisode_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homegenre',
            name='story',
        ),
        migrations.AddField(
            model_name='homeepisode',
            name='story',
            field=models.TextField(default=1, verbose_name='HomeGenre story'),
            preserve_default=False,
        ),
    ]
