# Generated by Django 4.1.6 on 2023-02-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_homegenre_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeepisode',
            name='homegenre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Full_list', to='pages.homegenre'),
            preserve_default=False,
        ),
    ]
